arquetipo/urls.py
from django.conf.urls import url

from . import views

app_name = 'arquetipo'

urlpatterns = [
        url( r'^$', views.index, name='index' ),
]

osb11/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url( r'^arquetipo/', include( 'arquetipo.urls' ) ),
    url(r'^admin/', admin.site.urls),
]

arquetipo/models.py
from django.db import models

# Create your models here.

arquetipo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.formsets import BaseFormSet

# datos basicos del proyecto Arquetype, artifact, etc
class FieldsForm( forms.Form ):
    organizacion = forms.CharField(
            required = True,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Nombre de la Organizacion',
                } ),
            )
    proyecto = forms.CharField(
            required = True,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Nombre del Proyecto',
                } ),
            )
    servicio = forms.CharField(
            required = True ,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Nombre del servicio',
                } ),
            )
    dominio = forms.CharField(
            required = True ,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Direccion del dominio',
                } ),
            )
# Operaciones
class OperationsForm( forms.Form ):
    operacion = forms.CharField(
            required = True,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Nombre de operacion'
                } ),
            )
# Tipos de datos
class DataTypesForm( forms.Form ):
    operacion = forms.CharField(
            required = True,
            widget = forms.TextInput( attrs = {
                'type':'number',
                'min':'1' ,
                'size': 1,
                } ),
    )
    CHOICES = ( ( '1', 'Request' ), ( '2', 'Response' ) )
    mensaje = forms.ChoiceField(
            required = True,
            widget = forms.RadioSelect,
            choices = CHOICES,
    )

    id_dato = forms.CharField(
            required = True,
            max_length = 20,
            widget = forms.TextInput( attrs = {
                'placeholder':'Nombre del dato'
            } ),
    )
    TYPES = ( ( 'integer', 'Integer' ),
        ( 'decimal', 'Decimal' ),
        ( 'string', 'String' ),
        ( 'token', 'Token' ),
        ( 'date', 'Date' ),
        ( 'time', 'Time' ),
        ( 'dateTime', 'Date Time' ),
        ( 'boolean', 'Boolean' ),
        ( 'anyURI', 'Any URI' ),
        ( 'complex', 'Complex' ),
     )
    tipo = forms.ChoiceField(
            required = True,
            choices = TYPES,
    )

arquetipo/views.py
import mimetypes
import os

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.forms.formsets import formset_factory
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from wsgiref.util import FileWrapper

from .forms import FieldsForm, OperationsForm, DataTypesForm
# Create your views here.
def index( request ):
    OperationsFormSet = formset_factory( OperationsForm )
    DataTypesFormSet = formset_factory( DataTypesForm )

    if request.method == 'POST':
        query_form = FieldsForm( request.POST )
        operations_formset = OperationsFormSet( request.POST, prefix='operations' )
        data_formset = DataTypesFormSet( request.POST, prefix='datas' )

        if query_form.is_valid() and operations_formset.is_valid() and data_formset.is_valid():
            group_id = query_form.cleaned_data.get( 'organizacion' )
            artifact_id = query_form.cleaned_data.get( 'proyecto' )
            version = "1.0-SNAPSHOT"
            nameSpace = query_form.cleaned_data.get( 'dominio' )
            service_name = query_form.cleaned_data.get( 'servicio' )

            operations_list = []

            for operation_form in operations_formset:
                operation = operation_form.cleaned_data.get( 'operacion' )
                if operation:
                    operations_list.append( operation )
            operations = ' '.join(operations_list)
            operations = "\"" + operations + "\""

            data_list = []

            for data in data_formset:
                operacion = data.cleaned_data.get( 'operacion' )
                mensaje = data.cleaned_data.get( 'mensaje' )
                dataName = data.cleaned_data.get( 'id_dato' )
                dataType = data.cleaned_data.get( 'tipo' )

                if operacion and mensaje and dataType and dataName:
                    dataToAdd = operacion + '-' + mensaje + '-' + dataName + '-' + dataType
                    data_list.append( dataToAdd )
            datas = ' '.join( data_list )
            datas = "\"" + datas + "\""
            print("%s" % datas)
            os.system( "yes | mvn archetype:generate -DarchetypeGroupId=nl.syntouch.examples.servicebus -DarchetypeArtifactId=MavenArchetypeService-archetype -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=%s -DartifactId=%s -DnameSpace=%s -Dversion=%s -Dfields=%s -Doperations=%s -DserviceName=%s" % ( group_id, artifact_id, nameSpace, version, datas, operations, service_name ) )
            os.system( "zip -r %s.zip %s" % ( artifact_id, artifact_id ) )
            os.system( "rm -rf %s" % artifact_id )
            os.system( "mv %s.zip media" % artifact_id )
            file = 'media/%s.zip' % artifact_id
            filename = os.path.basename( file )
            chunk_size = 8192
            response = HttpResponse( FileWrapper( open( file, 'rb' ), chunk_size ), content_type = mimetypes.guess_type( file )[0] )
            response[ 'Content-Lenght' ] = os.path.getsize( file )
            response[ 'Content-Disposition' ] = 'attachment; filename = %s' % filename
            return response
    else:
        query_form = FieldsForm
        operations_formset = OperationsFormSet( prefix='operations' )
        data_formset = DataTypesFormSet( prefix='datas' )

    context = { 'form': query_form, 'operations_formset': operations_formset, 'data_formset': data_formset }

    return render( request, 'arquetipo/index.html', context )

arquetipo/templates/arquetipo/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Generar Un Proyecto Telefonica {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'resources/css/styles.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Alegreya Sans' rel='stylesheet'>
        <link rel="icon" href="{% static 'resources/images/icon.png' %}" >
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block head %}
        {% endblock %}
    </head>
    <body>
      <div id="wrapper">
        <div class="page-header">
          <h1><a href="{% url 'arquetipo:index' %}"><img class="logo" src="{% static 'resources/images/company_logo.png'%}" height="42"></a></h1>
        </div>
        <div class="content container">
          <div class="row">
            <div class="col-md-8">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
        <div class="footer">
        </div>
      </div>
    </body>
</html>

arquetipo/templates/arquetipo/index.html
{% extends "arquetipo/base.html" %}

{% block content %}
<h1>Argumentos del proyecto</h1>
	<form method = "post" >
		<div class="fields">
			{% csrf_token%}
			{{ form.as_table }}
		</div>
		</br>
		<div class="maven-arguments">
			<div class="row">
				<div class="operations">
					<h1>Operaciones del proyecto</h1>
					{% for f_form in operations_formset %}
						<div class="operation-formset">
							{{ f_form.as_table }}
						</div>
					{% endfor %}
					{{ operations_formset.management_form }}
				</div>

				<div class="data">
					<h1>Datos</h1>
					{% for d_form in data_formset %}
						<div class="data-formset">
							<label> Número de Operacion</label>
							{{ d_form.operacion }}<br/>
							<label> Tipo de Operación </label>
							{{ d_form.mensaje }}
							<label>Id Dato</label>
							{{ d_form.id_dato }}
							<label>Tipo</label>
							{{ d_form.tipo }}
							<!-- {{ d_form.as_table }} -->
						</div>
					{% endfor %}
					{{ data_formset.management_form }}
				</div>
		</div>
	</div>
	</br>
		<button types='submit' value='generate'>Generar</button>
	</form>
{% load static %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'resources/js/jquery.formset.js' %}"></script>
<script>
	$('.operation-formset').formset({
		addText: 'Agregar una operación',
		deleteText: 'Eliminar',
		prefix: 'operations'
	});
	$('.data-formset').formset({
		addText: 'Agregar un dato',
		deleteText: 'Eliminar',
		prefix: 'datas'
	});
	</script>
{% endblock %}